title: "Hello, world! I'm Lindsey Dye"
description: > 
  Data Analyst | Sustainability Enthusiast  
  I explore the intersection of data, the environment, and storytelling.

permalink: ':title/'  # Controls how post URLs are generated

baseurl: ""  # Leave this empty if you're deploying to https://lmdye.github.io (i.e., not a project page)
url: "https://lmdye.github.io"  # Your full GitHub Pages URL

# Author Settings
author: Lindsey Dye
author-img: 15-retouch.jpg  # Make sure this image is in assets/img/
about-author: I am a data analyst passionate about sustainability, visualization, and storytelling with data.

# Social Media Handles (optional ones can be left blank or deleted)
social-twitter:       # add your Twitter handle (optional)
social-facebook:      # add your Facebook handle (optional)
social-github: lmdye
social-linkedin: lindsey-dye
social-email: dyel@umich.edu

# Disqus (optional)
discus-identifier:    # your Disqus shortname, if using comments

# Google Analytics (optional)
analytics:            # your Google Analytics Tracking ID

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
