title: "Hello, world! I'm Lindsey Dye"
description: Data Analyst | Sustainability Enthusiast 
permalink: ':title/'   # The structure for how your posts are linked, use this for custom URLs
baseurl: "/lmdye.github.io"  # The subpath for your site, e.g. /portfolio or /blog (use empty string if no subfolder)
url: "https://lmdye.github.io"  # Base URL for your site, replace with your actual URL

# Author Settings
author: Lindsey Dye  # Your name
author-img: 15-retouch.jpg # add your photo
about-author: I am a data analyst passionate about sustainability, visualization, and storytelling with data. # add description

social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: lmdye # add your Github handle
social-linkedin: lindsey-dye # add your Linkedin handle
social-email: dyel@umich.edu # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
