title: "Hello, world! I'm Lindsey Dye"
description: > 
  Data Analyst | Sustainability Enthusiast
  
permalink: ':title/'
baseurl: "" 
url: "https://lmdye.github.io" 

# Author Settings
author: Lindsey Dye
author-img: assets/img/25GOBLUE-36376658-15-retouch.png
about-author: "I am a data analyst passionate about sustainability, visualization, and storytelling with data."

# Social Links
social-github: lmdye 
social-linkedin: "in/lindsey-dye" 
social-email: "dyel@umich.edu" 

# Remove Disqus if not using
# discus-identifier: 

# Tracker
analytics: # Add your Google Analytics ID if needed

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
